//go:build windows

// Flying Saw Simulator for Windows: shows the single-file app (embedded below) in its own window,
// using the Microsoft Edge WebView2 runtime that ships with Windows 10 and 11. Without WebView2 the
// same page opens in the default browser instead.
package main

import (
	"bytes"
	_ "embed"
	"flag"
	"net/url"
	"os"
	"path/filepath"
	"time"
	"unsafe"

	webview2 "github.com/jchv/go-webview2"
	"golang.org/x/sys/windows"
)

// FlyingSaw.html is generated by build.py from index.html, styles.css, motion.js, app.js and the fonts.
//
//go:embed FlyingSaw.html
var page []byte

var version = "dev" // set by build.py through -ldflags

const title = "Flying Saw Simulator"

var (
	user32               = windows.NewLazySystemDLL("user32.dll")
	procGetDpiForSystem  = user32.NewProc("GetDpiForSystem")
	procSystemParamsInfo = user32.NewProc("SystemParametersInfoW")
)

func main() {
	smoke := flag.String("smoke", "", "test mode: load the page, write a JSON report to this file and exit")
	flag.Parse()

	// The page runs from a file in the user's local app data, so the browser engine keeps its saved
	// setup (localStorage) between runs. It is rewritten whenever a new version brings a new page.
	base, err := os.UserCacheDir()
	if err != nil {
		base = os.TempDir()
	}
	dir := filepath.Join(base, "FlyingSaw")
	htmlPath := filepath.Join(dir, "FlyingSaw.html")
	if err := writeIfChanged(htmlPath, page); err != nil {
		fail(*smoke, "cannot write "+htmlPath+": "+err.Error())
	}
	pageURL := (&url.URL{Scheme: "file", Path: "/" + filepath.ToSlash(htmlPath)}).String()

	scale := dpiScale()
	width, height := windowSize(scale)
	w := webview2.NewWithOptions(webview2.WebViewOptions{
		AutoFocus: true,
		DataPath:  filepath.Join(dir, "WebView2"),
		WindowOptions: webview2.WindowOptions{
			Title:  title + " " + version,
			Width:  width,
			Height: height,
			IconId: 1, // the icon resource that build.py links into the exe
			Center: true,
		},
	})
	if w == nil {
		if *smoke != "" {
			fail(*smoke, "WebView2 runtime not available")
		}
		message("Microsoft Edge WebView2 is not installed, so the simulator opens in your web browser instead.\n\n" +
			"To get the program window, install the WebView2 Runtime from\nhttps://go.microsoft.com/fwlink/p/?LinkId=2124703")
		openFile(htmlPath)
		return
	}
	w.SetSize(int(900*scale), int(600*scale), webview2.HintMin)
	if *smoke != "" {
		smokeTest(w, *smoke)
	}
	w.Navigate(pageURL)
	w.Run()
}

func writeIfChanged(path string, data []byte) error {
	if old, err := os.ReadFile(path); err == nil && bytes.Equal(old, data) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// dpiScale is the display scaling (1.0 at 100 %). The exe is per-monitor DPI aware (see its manifest),
// so window sizes are in physical pixels.
func dpiScale() float64 {
	if procGetDpiForSystem.Find() == nil {
		if dpi, _, _ := procGetDpiForSystem.Call(); dpi > 0 {
			return float64(dpi) / 96
		}
	}
	return 1
}

// windowSize opens the window at 1440×940 (scaled), but never larger than 92 % of the work area.
func windowSize(scale float64) (uint, uint) {
	w, h := 1440*scale, 940*scale
	var r struct{ Left, Top, Right, Bottom int32 }
	const spiGetWorkArea = 0x0030
	if ok, _, _ := procSystemParamsInfo.Call(spiGetWorkArea, 0, uintptr(unsafe.Pointer(&r)), 0); ok != 0 {
		w = min(w, float64(r.Right-r.Left)*0.92)
		h = min(h, float64(r.Bottom-r.Top)*0.92)
	}
	return uint(w), uint(h)
}

func message(text string) {
	t, _ := windows.UTF16PtrFromString(text)
	c, _ := windows.UTF16PtrFromString(title)
	_, _ = windows.MessageBox(0, t, c, windows.MB_OK|windows.MB_ICONINFORMATION)
}

func openFile(path string) {
	verb, _ := windows.UTF16PtrFromString("open")
	file, _ := windows.UTF16PtrFromString(path)
	_ = windows.ShellExecute(0, verb, file, nil, nil, windows.SW_SHOWNORMAL)
}

func fail(smoke, msg string) {
	if smoke != "" {
		_ = os.WriteFile(smoke, []byte(`{"error":`+jsonString(msg)+`}`), 0o644)
		os.Exit(3)
	}
	message(msg)
	os.Exit(1)
}

func jsonString(s string) string {
	b := []byte{'"'}
	for _, r := range s {
		switch {
		case r == '"' || r == '\\':
			b = append(b, '\\', byte(r))
		case r < 0x20:
			b = append(b, ' ')
		default:
			b = append(b, string(r)...)
		}
	}
	return string(append(b, '"'))
}

// smokeTest is used by CI on a Windows runner: once the page has loaded, it reports what the page
// shows and whether storage and fonts work, then closes the window.
func smokeTest(w webview2.WebView, out string) {
	_ = w.Bind("flyingSawSmoke", func(report string) {
		_ = os.WriteFile(out, []byte(report), 0o644)
		w.Terminate()
	})
	w.Init(`(function () {
  const errors = [];
  window.addEventListener('error', e => errors.push(String(e.message)));
  window.addEventListener('load', () => setTimeout(() => {
    const $ = id => document.getElementById(id);
    let storage = false;
    try { localStorage.setItem('smoke', '1'); storage = localStorage.getItem('smoke') === '1'; localStorage.removeItem('smoke'); } catch (e) {}
    flyingSawSmoke(JSON.stringify({
      pill: $('pill').textContent, msg: $('vmsg').textContent,
      inputs: document.querySelectorAll('#groups input').length,
      copyLinkHidden: $('copyLink').hidden, protocol: location.protocol, storage,
      fonts: document.fonts.check('600 20px "Barlow Condensed"') && document.fonts.check('400 16px Barlow'),
      width: innerWidth, dpr: devicePixelRatio, errors,
    }));
  }, 1500));
})();`)
	go func() {
		time.Sleep(60 * time.Second)
		fail(out, "timed out waiting for the page")
	}()
}
